### ISSUE TITLE
Branch for 5.5.2

### ISSUE THREAD

**Issue by lazlyhu** [skroutz/elasticsearch-skroutz-greekstemmer#27]
Hi!

Could you compile a new branch for ES 5.5.2?

Thank you :)

**Comment by lovemeblender** [comment]
Hello!

We don't currently support ES5.5.2 but assuming that there aren't any major changes it would be as easy as changing the version to the plugin's pom file. 

Please do let us know if you're having any issues!

**Comment by lazlyhu** [comment]
Hi!

Thank you the fast reaction! 🙇 😃 

Yes, I'm thinking the same, but ES refuse the install because the version numbers only if I'm right. Maybe you just need to rewrite the version, but I don't have maven (yet) to compile new version and try it. I thought maybe better if you do it, and you can add it to your repo, later others can use without discover forks if looking for this.
https://github.com/skroutz/elasticsearch-skroutz-greekstemmer/compare/5.4.2...lazlyhu:5.5.2

```
Exception in thread "main" java.lang.IllegalArgumentException: plugin [elasticsearch-skroutz-greekstemmer] is incompatible with version [5.5.2]; was designed for version [5.4.2]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:474)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:543)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:217)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:201)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

Thank you again, have a nice weekend.

**Comment by lazlyhu** [comment]
@lovemeblender Please create an empty 5.5.2 branch on your repo, so I can give you PR for that repo directly. :)
